name: Update Chocolatey Releases
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        type: string
        default: "v8.0.0"
  repository_dispatch:
    types: [update]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # Checkout the branch
      - name: checkout
        uses: actions/checkout@v3
      # Determine which version should be released based on event type
      - name: Set Version (Workflow Dispatch)
        shell: bash
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo VERSION=${{ inputs.version }} >> $GITHUB_ENV
      - name: Set Version (Repository Dispatch)
        if: github.event_name == 'repository_dispatch'
        shell: bash
        run: |
          echo VERSION=${{ github.event.client_payload.version }} >> $GITHUB_ENV
      - name: Unified Version
        id: version
        shell: bash
        run: |
          echo "Version: $VERSION"
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - uses: addnab/docker-run-action@v3
        with:
          image: chocolatey/choco:latest
          options: -v ${{ github.workspace }}:/packages -e CHOCO_API_KEY=${{ secrets.CHOCOLATEY_API_KEY }}
          run: |
            for pkg in cnquery cnspec; do
              echo "------- PROCESSING ${pkg} ----------------------"
              cd /packages/$pkg
              choco apikey --key ${CHOCO_API_KEY} --source https://push.chocolatey.org/
              choco pack
              #choco push  ##<--- Disable this for testing
            done


